// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAFo77gJ2nJABA6Qa6J4C0HqQtTOWbss',
    appId: '1:2770988839:web:e3a2afc96d97a9d8160302',
    messagingSenderId: '2770988839',
    projectId: 'lensmatch-a2dbc',
    authDomain: 'lensmatch-a2dbc.firebaseapp.com',
    storageBucket: 'lensmatch-a2dbc.firebasestorage.app',
    measurementId: 'G-3Y10KWF403',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUSLeHFGaMISG6LpXhG8FAdc42okxxnA',
    appId: '1:2770988839:android:6eae6445a0c8e487160302',
    messagingSenderId: '2770988839',
    projectId: 'lensmatch-a2dbc',
    storageBucket: 'lensmatch-a2dbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mTN9FkUgjATTMphDCLjpm-no9KPH96I',
    appId: '1:2770988839:ios:8c78ac8b76c9a1a5160302',
    messagingSenderId: '2770988839',
    projectId: 'lensmatch-a2dbc',
    storageBucket: 'lensmatch-a2dbc.firebasestorage.app',
    iosBundleId: 'com.franselle.lensmatch.lensmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mTN9FkUgjATTMphDCLjpm-no9KPH96I',
    appId: '1:2770988839:ios:8c78ac8b76c9a1a5160302',
    messagingSenderId: '2770988839',
    projectId: 'lensmatch-a2dbc',
    storageBucket: 'lensmatch-a2dbc.firebasestorage.app',
    iosBundleId: 'com.franselle.lensmatch.lensmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqAFo77gJ2nJABA6Qa6J4C0HqQtTOWbss',
    appId: '1:2770988839:web:f5064297cd954534160302',
    messagingSenderId: '2770988839',
    projectId: 'lensmatch-a2dbc',
    authDomain: 'lensmatch-a2dbc.firebaseapp.com',
    storageBucket: 'lensmatch-a2dbc.firebasestorage.app',
    measurementId: 'G-68YRRPWX4P',
  );
}
